symptoms = [
    "headache",
    "fever",
    "nausea",
    "vomiting",
    "dizziness",
    "fatigue",
    "chest pain",
    "shortness of breath",
    "rash",
    "itching",
    "swelling",
    "diarrhea",
    "abdominal pain",
    "cough",
    "sore throat",
    "weakness",
    "blurred vision",
    "anxiety",
    "palpitations",
    "back pain",
    "joint pain",
    "muscle pain"
]
